events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;

    # Configuração do Servidor
    server {
        listen 80;
        server_name api.newlifefibra.com.br localhost;

        # O Nginx vai passar a requisição real para o Fiber, incluindo os IPs dos clientes
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # -------------------------------------------------------------
        # ROTEAMENTO PARA AS APIs
        # -------------------------------------------------------------

        # API 1: Consulta de Cliente
        # Redireciona tudo que chega em /consulta para o contêiner mk-api-consulta-doc
        location /consulta {
            proxy_pass http://mk-api-consulta-doc:8080;
        }

        # API 2: Conexões do Cliente
        location /conexoes {
            proxy_pass http://mk-api-conexoes:8080;
        }

        # Exemplo para a API 2: Faturas
        # location /api/v1/fatura/ {
        #     proxy_pass http://mk-api-faturas:8080;
        # }
        
        # Exemplo para a API 3: Atendimentos
        # location /api/v1/atendimento/ {
        #     proxy_pass http://mk-api-atendimentos:8080;
        # }

        # Caso a rota não seja encontrada em nenhuma API
        location / {
            return 404 "{\"error\": \"Endpoint not mapped in reverse proxy\"}";
        }
    }
}
